name: First Workflow

on: 
  push: 
    branches: 
    - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: print welcome message
        run: echo "welcome to our firt github Actions Workflowa"
      - name: Checkout repository 
        uses: actions/checkout@v4.2.2
      - name : List repository files
        run: ls -la
